#!/usr/bin/env python3
"""Manage the idea backlog that feeds the production tree.

    python3 scripts/social/ideas.py                        # regenerate INDEX.md
    python3 scripts/social/ideas.py --new "Title" --series "Series name"
    python3 scripts/social/ideas.py --set I001 --status approved
    python3 scripts/social/ideas.py --set I001 --style 2
    python3 scripts/social/ideas.py --link I001 --production 0036

An idea is a proposal, not a request. It carries a hook, a script sketch and an
honest note on what could go wrong, so it can be judged before any credits are
spent. Approving one is what turns it into a production.

registry.json is the source of truth; INDEX.md is generated from it plus a scan
of what is actually on disk.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
IDEAS = REPO / "ideas"
REG = IDEAS / "registry.json"

# proposed -> approved -> delivered -> published, with rejected as the dead end.
# Only the user moves an idea past `proposed`; nothing self-approves.
STATUSES = ["proposed", "approved", "delivered", "published", "rejected"]
STATUS_ICON = {
    "proposed": "·", "approved": "+", "delivered": "✓",
    "published": "★", "rejected": "✗",
}

# mirrors productions.py — the user names the style, it is never guessed
STYLES = {
    1: "Cinematic Reverent",
    2: "Quiet Observational",
    3: "Dua Teaching",
    4: "Animated Nasheed",
    5: "Image Post",
    7: "Photoreal Sing-Along",
}


def today() -> str:
    return _dt.date.today().isoformat()


def slugify(text: str) -> str:
    s = re.sub(r"[^\w\s-]", "", text, flags=re.UNICODE)
    s = re.sub(r"[\s_]+", "-", s.strip())
    return re.sub(r"-{2,}", "-", s).strip("-").lower()


def load() -> dict:
    if not REG.exists():
        return {"ideas": []}
    reg = json.loads(REG.read_text())
    for e in reg.get("ideas", []):
        e.setdefault("style", None)
        e.setdefault("production", None)
        e.setdefault("series", None)
        e.setdefault("history", [])
    return reg


def save(reg: dict) -> None:
    reg["ideas"].sort(key=lambda e: e["id"])
    REG.write_text(json.dumps(reg, indent=2, ensure_ascii=False) + "\n")


def find(reg: dict, ident: str) -> dict | None:
    """Accept I007, i7 or 7 — anything that resolves to one id."""
    want = ident.upper().lstrip("I").lstrip("0") or "0"
    for e in reg["ideas"]:
        if e["id"].lstrip("I").lstrip("0") == want:
            return e
    return None


def next_id(reg: dict) -> str:
    n = max((int(e["id"][1:]) for e in reg["ideas"]), default=0) + 1
    return f"I{n:03d}"


def note(entry: dict, what: str) -> None:
    entry["history"].append({"date": today(), "event": what})


def style_label(n) -> str:
    if not n:
        return "unstyled"
    return f"Style {n} — {STYLES.get(int(n), 'unknown')}"


def idea_file(entry: dict) -> Path:
    return IDEAS / f"{entry['id']}-{entry['slug']}.md"


def read_hook(path: Path) -> str:
    """Pull the one-line hook out of an idea file for the index."""
    if not path.exists():
        return ""
    grab = False
    for line in path.read_text().splitlines():
        if line.startswith("## Hook"):
            grab = True
            continue
        if grab:
            if line.startswith("##"):
                break
            s = line.strip().lstrip("> ").strip()
            if s:
                return s
    return ""


def index(reg: dict) -> str:
    ideas = reg["ideas"]
    by_series: dict[str, list[dict]] = {}
    for e in ideas:
        by_series.setdefault(e.get("series") or "Unfiled", []).append(e)

    counts = {s: sum(1 for e in ideas if e["status"] == s) for s in STATUSES}
    tally = " · ".join(f"{counts[s]} {s}" for s in STATUSES if counts[s])

    L = [
        "# Ideas — Index",
        "",
        "Generated by `scripts/social/ideas.py`. Standard:",
        "[IDEA-STANDARD.md](IDEA-STANDARD.md)",
        "",
        "Every row is one proposal. Open the file for the hook, the script sketch,",
        "why it should convert, and an honest note on what could go wrong.",
        "",
        "An idea is **not** a request. Nothing here is built until you approve it,",
        "and nothing self-approves. Approving one creates a production in",
        "[productions/](../productions/INDEX.md) and the two stay linked.",
        "",
        "Legend: `·` proposed · `+` approved · `✓` delivered · `★` published · `✗` rejected",
        "",
        f"**{len(ideas)} ideas** — {tally}",
        "",
    ]

    for series in sorted(by_series):
        L += [f"## {series}", "",
              "| # | Idea | Status | Style | Production | Hook |",
              "| --- | --- | --- | --- | --- | --- |"]
        for e in sorted(by_series[series], key=lambda x: x["id"]):
            f = idea_file(e)
            icon = STATUS_ICON.get(e["status"], "?")
            style = f"{e['style']}" if e.get("style") else "—"
            prod = e.get("production")
            prod = (f"[`{prod}`](../productions/INDEX.md)" if prod else "—")
            hook = read_hook(f).replace("|", "\\|")
            if len(hook) > 84:
                hook = hook[:83].rstrip() + "…"
            L.append(f"| `{e['id']}` | [{e['title']}]({f.name}) | {icon} {e['status']} "
                     f"| {style} | {prod} | {hook} |")
        L.append("")

    L += [
        "## Moving an idea forward",
        "",
        "```bash",
        "python3 scripts/social/ideas.py --set I001 --status approved",
        "python3 scripts/social/ideas.py --set I001 --style 2      # you name the style",
        "python3 scripts/social/ideas.py --link I001 --production 0036",
        "```",
        "",
        "`delivered` and `published` are set on the idea only after the linked",
        "production reaches that state, so the two trees never disagree.",
        "",
    ]
    return "\n".join(L)


def write_index(reg: dict) -> None:
    IDEAS.mkdir(exist_ok=True)
    (IDEAS / "INDEX.md").write_text(index(reg))
    print(f"wrote ideas/INDEX.md ({len(reg['ideas'])} ideas)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--new", metavar="TITLE")
    ap.add_argument("--series", metavar="NAME", help="grouping, used with --new")
    ap.add_argument("--set", metavar="ID")
    ap.add_argument("--status", choices=STATUSES)
    ap.add_argument("--style", type=int, choices=list(STYLES),
                    help="finishing style (see library/STYLES.md). Never guessed — "
                         "the user names it")
    ap.add_argument("--link", metavar="ID", help="attach an idea to a production")
    ap.add_argument("--production", metavar="NNNN",
                    help="production number, use with --link")
    ap.add_argument("--show", metavar="ID", help="print one idea's registry entry")
    ap.add_argument("--statuses", action="store_true",
                    help="list the status lifecycle and exit")
    a = ap.parse_args()

    if a.statuses:
        print("proposed  · nobody has committed to it yet")
        print("approved  + you said build it; it becomes a production")
        print("delivered ✓ the production is finished and verified")
        print("published ★ it is live on at least one platform")
        print("rejected  ✗ decided against, kept so it is not re-proposed")
        return 0

    reg = load()

    if a.new:
        e = {"id": next_id(reg), "title": a.new, "slug": slugify(a.new),
             "series": a.series, "status": "proposed", "style": None,
             "production": None, "created": today(), "history": []}
        note(e, "proposed")
        reg["ideas"].append(e)
        save(reg)
        print(f"{e['id']} {e['title']}\n  file: ideas/{idea_file(e).name}")

    if a.set:
        e = find(reg, a.set)
        if not e:
            print(f"no idea {a.set}")
            return 1
        if a.status:
            e["status"] = a.status
            note(e, a.status)
            print(f"{e['id']} -> {a.status}")
        if a.style:
            e["style"] = a.style
            note(e, f"style {a.style}")
            print(f"{e['id']} -> {style_label(a.style)}")
        if not (a.status or a.style):
            print("--set needs --status or --style")
            return 1
        save(reg)

    if a.link:
        e = find(reg, a.link)
        if not e:
            print(f"no idea {a.link}")
            return 1
        if not a.production:
            print("--link needs --production")
            return 1
        e["production"] = a.production
        if e["status"] == "proposed":
            e["status"] = "approved"
            note(e, "approved")
        note(e, f"linked to production {a.production}")
        save(reg)
        print(f"{e['id']} {e['title']}\n  production: {a.production}  ({e['status']})")

    if a.show:
        e = find(reg, a.show)
        if not e:
            print(f"no idea {a.show}")
            return 1
        print(json.dumps(e, indent=2, ensure_ascii=False))
        return 0

    write_index(reg)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
